
@base_url=http://127.0.0.1:5000
GET {{base_url}}/api/cupcakes

##########


# @name posted_cupcake
POST {{base_url}}/api/cupcakes
Content-Type: application/json

{
    "flavor":"cola",
    "rating":3,
    "size":2,
    "image": "http://bla.com"
}

####

GET {{base_url}}/api/cupcake/{{posted_cupcake.response.body.cupcake.id}}


####

PATCH {{base_url}}/api/cupcake/{{posted_cupcake.response.body.cupcake.id}}
Content-Type: application/json

{
    "flavor":"cola",
    "rating":5,
    "size":2,
    "image": "http://bla.com"
}

####

DELETE {{base_url}}/api/cupcake/{{posted_cupcake.response.body.cupcake.id}}
